### ISSUE TITLE
Community Stacks - Build error on cloud.docker.com - post_push hook - No such file or directory

### ISSUE THREAD

**Issue by tlinnet** [jupyter/cookiecutter-docker-stacks#2]
Hi !

I am trying your new guide for [Community Stacks](https://jupyter-docker-stacks.readthedocs.io/en/latest/contributing/stacks.html).

It's very well written!

I aim for a little project to bring C# to Jupyter Notebook. To try it out easily.
* Github repo: [github.com/tlinnet/csharp-notebook](https://github.com/tlinnet/csharp-notebook)
* Cloud Docker: [cloud.docker.com/repository/docker/tlinnet/csharp-notebook](https://cloud.docker.com/repository/docker/tlinnet/csharp-notebook)

When I try to build on cloud.docker.com, I get an error.

```
Done building project "/icsharp/iCSharp.sln".
Build succeeded.
0 Warning(s)
0 Error(s)
Time Elapsed 00:00:44.5250460
Removing intermediate container 0be778c8290f
---> e9e1e0c44f40
Step 6/8 : RUN chown -R $NB_USER:users $HOME/.local && chown -R $NB_USER:users $HOME/.mono && chown -R $NB_USER:users $HOME/.nuget && echo '{' > /icsharp/kernel-spec/kernel.json && echo ' "argv": ["mono", "/icsharp/build/Release/bin/iCSharp.Kernel.exe", "{connection_file}"],' >> /icsharp/kernel-spec/kernel.json && echo ' "display_name": "C#",' >> /icsharp/kernel-spec/kernel.json && echo ' "language": "csharp"' >> /icsharp/kernel-spec/kernel.json && echo '}' >> /icsharp/kernel-spec/kernel.json
---> Running in 275eef437144
Removing intermediate container 275eef437144
---> c2b6d3bbd9c1
Step 7/8 : USER $NB_USER
---> Running in 6f3ad61d6409
Removing intermediate container 6f3ad61d6409
---> 21cc03db1a83
Step 8/8 : RUN cd /icsharp && jupyter-kernelspec install --user kernel-spec
---> Running in 9a91d96d4d41
[InstallKernelSpec] Installed kernelspec kernel-spec in /home/jovyan/.local/share/jupyter/kernels/kernel-spec
Removing intermediate container 9a91d96d4d41
---> d3ce35014d12
Successfully built d3ce35014d12
Successfully tagged tlinnet/csharp-notebook:latest
Pushing index.docker.io/tlinnet/csharp-notebook:latest...
Done!
Executing post_push hook...
Unexpected error
Encountered error: [Errno 2] No such file or directory
Traceback (most recent call last):
File "/stage/builder/runner.py", line 292, in _run
self.push()
File "/stage/builder/runner.py", line 246, in push
hooks.run('post_push')
File "/stage/builder/hooks.py", line 21, in run
utils.execute_command(hook_path, '{} hook failed!'.format(name))
File "/stage/builder/utils.py", line 43, in execute_command
bufsize=1)
File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
raise child_exception
OSError: [Errno 2] No such file or directory
```

The post_push folder is part of the repo, and looks normal.

**Comment by jakirkham** [comment]
Something like [this]( https://github.com/conda-forge/conda-smithy/blob/32fc60fced511fefa0e2d4515083fe7cabb14db2/conda_smithy/feedstock_content/.gitattributes#L5-L7 ) might be useful.
